name: clean_architecture_lints
environment:
  sdk: '>=3.0.0 <4.0.0'

dependency_overrides:
  recase: 4.0.0

dependencies:
  collection:
  # we will use analyzer for inspecting Dart files
  analyzer: 5.13.0
  analyzer_plugin: 0.11.2


dev_dependencies:
  lint: 2.3.0